### ISSUE TITLE
Substreams cannot write from server to client if using binary parser

### ISSUE THREAD

**Issue by bodjkin** [primus/substream#10] opened 2015-05-30 12:53 UTC
Easy to replicate with a slight modification to the example code:

```javascript
primus = new Primus(server, {
  transformer: 'engine.io',
  parser: 'binary', // <- added to example
});

primus.use('substream', require('../'));

// stuff...

var foo = spark.substream('foo');
foo.on('data', function(data) {
  console.log('foo received:', data, ++count, spark.id);

  // Not received on the client, no errors on server, just quietly eats data
  foo.write('Curse your sudden but inevitable betrayal');
});
```

**Comment by lpinca** [comment] 2015-05-30 19:12
Nice catch!
This patch https://github.com/binaryjs/node-binarypack/pull/5 should fix the issue.

**Comment by bodjkin** [comment] 2015-05-30 22:16
Awesome! Thanks for the quick fix.

**Comment by bodjkin** [comment] 2015-05-30 22:21
Actually I suppose I should leave this open until someone at the binaryjs organization merges your pull request in.

**Comment by lpinca** [comment] 2015-05-31 06:27
Another way to fix the issue, if the pull request doesn't get merged, is to make substream work with browserify.

**Comment by bodjkin** [comment] 2015-05-31 23:47
Do you mean for applying the patch? Your patch works fine for my purposes, but for the benefit of anyone else that might want to use this module with the binary parser, it would make sense to leave this open until the issue is resolved for default, unpatched installations, right? If you're not concerned about it, I can close it again.

**Comment by lpinca** [comment] 2015-06-01 05:45
@bodjkin no, leave this open until the issue is fixed.

I was referring to the fact that there is another way to fix this without patching `node-binarypack`.

**Closed** 2015-06-17 07:35 UTC
